### ISSUE TITLE
Please rename your project

### ISSUE THREAD

**Issue by muesliq** [go-spatial/atlante#116]
Hi,

"Maptoolkit" is a trademark used since 2008 by the company Toursprung GmbH. See https://www.maptoolkit.net/ and https://www.toursprung.com/en/technology/. 

It also powers services that create printable maps from MVT, see https://www.printmaps.net.

Please be so kind and rename your project.

**Comment by ARolek** [comment]
@muesliq we're not particularly tied to the name, so I don't have a problem making a name change. This project is not an immediate focus of ours right now (will likely be in a few months) and any name change will require us to make CI/CD updates as well. We will think about a name change and make adjustments accordingly. 

Good luck with your maptoolkit!

**Comment by muesliq** [comment]
Thanks for your understanding!

**Comment by ARolek** [comment]
Repo has been renamed.
